djherokudocker/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("pages.urls", namespace="pages")),
    path("admin/", admin.site.urls),
]

if bool(settings.DEBUG):
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

pages/urls.py
from django.urls import path

from pages.views import about_view, home_view

app_name = "pages"

urlpatterns = [
    path("", home_view, name="home"),
    path("about/", about_view, name="about"),
]

pages/models.py
# from django.db import models

# Create your models here.

pages/views/about.py
from django.shortcuts import render


def about_view(request):
    context = {"title": "About Page"}
    return render(request, "pages/about.html", context)

pages/views/home.py
from django.shortcuts import render


def home_view(request):
    context = {"title": "Home Page"}
    return render(request, "pages/home.html", context)

pages/templates/pages/about.html
{% extends 'base/base.html' %}
    
{% block content %}
    <h2>About Page</h2>
{% endblock content %}

pages/templates/pages/home.html
{% extends 'base/base.html' %}
    
{% block content %}
    <h2>Home Page</h2>
{% endblock content %}
    

templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css'%}">
    <title>
        {% block title %}
            {% if title %}
                {{ title }}
            {% endif %}  
        {% endblock title %}
            
    </title>
</head>
<body>
    <div class="site">
        <div class="site-header">
            {% include 'partials/_nav.html' %}
        </div>
        <main class="site-content">
            <div class="container">
                {% block content %}
                    
                {% endblock content %}  
            </div>
        </main>
        <footer class="site-footer bg-primary">
            {% include 'partials/_footer.html' %}
        </footer>
    </div>
    {% block script %}
        <script defer src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <script defer src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
        <script defer src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    {% endblock script %}
</body>
</html>

templates/partials/_footer.html
<div class="container">
    <p>
        Copyright &copy;<script>document.write(new Date().getFullYear());</script>
        All rights reserved by <a href="{% url 'pages:home' %}">DjDocker</a>.
    </p>
</div>

templates/partials/_nav.html
<nav class="navbar navbar-expand-sm bg-primary sticky-top navbar-dark">
    <a href="{% url 'pages:home'%}" class="navbar-brand">DjDocker</a>
    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#collapsibleNav">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" class="collapsibleNav">
        <ul class="navbar-nav">
            <li class="nav-item"><a class="nav-link" href="{% url 'pages:home'%}">Home</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'pages:about'%}">About</a></li>
        </ul>
    </div>
</nav>